/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package constants;

/**
 *
 * @author Katie Lin
 */
public class SpecificText {
    public static final String DEFAULT_TITLE = "Please select an option below";
    
    //Button 1
    public static final String TEAM_QUERY_ALL = "Retrieved total revenue generated by each team.";
    public static final String TEAM_QUERY_ONE = "Retrieved total revenue generated by the ";
    
    //Button 2
    public static final String PLAYER_SALES_P1 = "Retrieving the number of customers that have purchased any products from ";
    public static final String PLAYER_SALES_P2 = " of the ";
    //Button 3
    public static final String PRODUCTS_PURCHASED = "Retrieving all customers that have purchased product with ID ";
    //Button 4
    public static final String TRANSFER_WAREHOUSE_P1 = "Successfully moved ";
    public static final String TRANSFER_WAREHOUSE_P2 = " products with id ";
    public static final String TRANSFER_WAREHOUSE_P3 = " from ";
    public static final String TRANSFER_WAREHOUSE_P4 = " to ";
    //Button 5
    
    //Button 6
}
